#!/bin/bash
cd "../$( dirname "${BASH_SOURCE[0]}" )" && pwd
. run/_settings

mvn -e clean install \
-Pjbehave-story-run \
${httpProxy:+-DHTTP_PROXY=${httpProxy} }\
${remoteWebDriverURL:+-DREMOTE_WEBDRIVER_URL=${remoteWebDriverURL} }\
${browserVersion:+-Dbrowser.version=${browserVersion:-10} }\
${domainToTestDotcom:+-DdomainToTest=${domainToTestDotcom} }\
${domainToTestSwabiz:+-DswabizDomainToTest=${domainToTestSwabiz} }\
${storyTimeoutInSecs:+-DstoryTimeoutInSecs=${storyTimeoutInSecs:-1200} }\
${threads:+-Dthreads=${threads:-5} }\
${EXTRA_MVN_DEFINES:+$EXTRA_MVN_DEFINES }\
\
-DDYNA_STUBS \
-Dlocal.screenshot -DMOBILE_BOARDING_PASS -DANTI_FRAUD_TOGGLE_SVC \
-Dmeta.filter="groovy: project == 'mbp' && dyna_stubs && !not_passing" \
$*
