#!/bin/bash
cd "../$( dirname "${BASH_SOURCE[0]}" )" && pwd
. run/_settings

mvn -e clean install \
-Pjbehave-story-run \
${httpProxy:+-DHTTP_PROXY=${httpProxy} }\
${remoteWebDriverURL:+-DREMOTE_WEBDRIVER_URL=${remoteWebDriverURL} }\
${browserVersion:+-Dbrowser.version=${browserVersion:-10} }\
${domainToTestDotcom:+-DdomainToTest=${domainToTestDotcom} }\
${domainToTestSwabiz:+-DswabizDomainToTest=${domainToTestSwabiz} }\
${storyTimeoutInSecs:+-DstoryTimeoutInSecs=${storyTimeoutInSecs:-1200} }\
${threads:+-Dthreads=${threads:-5} }\
${EXTRA_MVN_DEFINES:+$EXTRA_MVN_DEFINES }\
\
-DDYNA_STUBS \
-DRR_ENROLL_MAINTENANCE_ON -DRR_EDIT_MAINTENANCE_ON -DAIR_VIEW_MAINTENANCE_ON \
-Dmeta.filter="groovy: project == 'SWAT_Maintenance' && dyna_stubs == true && project_in_dev" \
$*
