#!/bin/bash
cd "../$( dirname "${BASH_SOURCE[0]}" )" && pwd
. run/_settings

mvn -e clean install \
-Pjbehave-story-run \
-DHTTP_PROXY=${httpProxy} \
-DREMOTE_WEBDRIVER_URL=${remoteWebDriverURL} \
-Dbrowser.version=${browserVersion:-10} \
-DdomainToTest=${domainToTestDotcom} \
-DswabizDomainToTest=${domainToTestSwabiz} \
-DstoryTimeoutInSecs=${storyTimeoutInSecs:-1200} \
-Dthreads=${threads:-5} \
${EXTRA_MVN_DEFINES:-''} \
\
-Dmeta.filter="groovy: dyna_stubs && !not_passing && project == 'lfcsops'" \
-DDYNA_STUBS \
$* 2>&1 | tee /tmp/$0.log

exit 3
-DstoryFilter=dyna_stub_verify_schedule_not_published
