#!/bin/bash
cd "../$( dirname "${BASH_SOURCE[0]}" )" && pwd
. run/_settings

mvn -e clean install \
-Pjbehave-story-run \
${httpProxy:+-DHTTP_PROXY=${httpProxy} }\
${remoteWebDriverURL:+-DREMOTE_WEBDRIVER_URL=${remoteWebDriverURL} }\
${browserVersion:+-Dbrowser.version=${browserVersion:-10} }\
${domainToTestDotcom:+-DdomainToTest=${domainToTestDotcom} }\
${domainToTestSwabiz:+-DswabizDomainToTest=${domainToTestSwabiz} }\
${storyTimeoutInSecs:+-DstoryTimeoutInSecs=${storyTimeoutInSecs:-1200} }\
${threads:+-Dthreads=${threads:-1} }\
${EXTRA_MVN_DEFINES:+$EXTRA_MVN_DEFINES }\
\
-Dmeta.filter="groovy: flow == 'air' && process == 'booking' && dyna_stubs && !not_passing && !suite && !project_in_dev && !seatSelection && !accordion_purchase_page && !airTranOnly" \
-DDYNA_STUBS \
$* 2>&1 | tee /tmp/$0.log

