#!/bin/bash
export basedir="$HOME/work/commerce-git/commerce-project/jbehave-webdriver/air"
cd $HOME/work/commerce-git/commerce-project/jbehave-webdriver/air || $( echo "could not cd to $basedir" && exit 2 )
. run/_settings

mvn -e clean install \
-Pjbehave-story-run \
${httpProxy:+-DHTTP_PROXY=${httpProxy} }\
${remoteWebDriverURL:+-DREMOTE_WEBDRIVER_URL=${remoteWebDriverURL} }\
${browserVersion:+-Dbrowser.version=${browserVersion:-10} }\
${domainToTestDotcom:+-DdomainToTest=${domainToTestDotcom} }\
${domainToTestSwabiz:+-DswabizDomainToTest=${domainToTestSwabiz} }\
${storyTimeoutInSecs:+-DstoryTimeoutInSecs=${storyTimeoutInSecs:-1200} }\
${threads:+-Dthreads=${threads:-1} }\
${EXTRA_MVN_DEFINES:+$EXTRA_MVN_DEFINES }\
-Dmeta.filter="groovy: suite == 'faultInjection' && !not_passing" \
-Dfault.testing \
$*
exit 0
#-DDYNA_STUBS \
#-Dmeta.filter="groovy: suite == 'faultInjection' && !not_passing" \
#-DstoryFilter='rapid_rewards_purchase_dollars_hibernateException.story' \
#-Dmeta.filter="groovy: suite == 'faultInjection' && !not_passing" \
